apiVersion: v1
kind: Service
metadata:
  name: activemq-artemis-service
spec:
  selector:
    app: activemq-artemis
  ports:
    - protocol: TCP
      port: 61616
      targetPort: 61616
  type: ClusterIP

